# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.landrush.enabled = true
  config.landrush.tld = 'boink.io'

  config.vm.box = "EliasGoldberg/centos6"
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.define "vimes" do |vimes|
    vimes.vm.hostname = "vimes.boink.io"
  end

  config.vm.define "colon" do |colon|
    colon.vm.hostname = "colon.boink.io"
  end  

  config.vm.define "nobbs" do |nobbs|
    nobbs.vm.hostname = "nobbs.boink.io"
  end  

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  #config.vm.box = "EliasGoldberg/centos6"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo iptables -I INPUT 1 -p tcp --dport 9200 -j ACCEPT
    sudo iptables -I INPUT 1 -p tcp --dport 9300 -j ACCEPT
    sudo service iptables save
    sudo service network restart
    
    sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

    echo -e "[elasticsearch-1.5]\nname=Elasticsearch repository for 1.5.x packages\nbaseurl=http://packages.elastic.co/elasticsearch/1.5/centos\ngpgcheck=1\ngpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch\nenabled=1\n" | sudo tee -a /etc/yum.repos.d/elasticsearch.repo

    sudo yum -y install elasticsearch
    sudo /usr/share/elasticsearch/bin/plugin -i elasticsearch/marvel/latest

    echo -e '
      network.host: _eth1:ipv4_
      discovery.zen.ping.multicast.enabled: false
      discovery.zen.ping.unicast.hosts: ["vimes.boink.io","colon.boink.io","nobbs.boink.io"]
    ' | sudo tee -a /etc/elasticsearch/elasticsearch.yml
    sudo chkconfig --add elasticsearch
    sudo service elasticsearch start
  SHELL

  #config.vm.provision "puppet" do |puppet|
  #  puppet.module_path = "modules"
  #end
end
